### ISSUE TITLE
Are we ready to finalize this extraction and start a PR merging into the manifest?

### ISSUE THREAD

**Issue by aarongustafson** [w3c/image-resource#10]
It’s been a bit and I wanted to follow up. I’d like to get the ball rolling again.

**Comment by rayankans** [comment]
Looks fine to me. All the issues unrelated to new functionality have been resolved.

**Comment by rayankans** [comment]
@marcoscaceres ping

**Comment by marcoscaceres** [comment]
We should probably just get manifest to point to this, right?

**Comment by rayankans** [comment]
I thought we'd move this to w3.org before making other specs point to this.

I'll file issues against specs using `ImageResource` to point to this definition instead.

**Comment by marcoscaceres** [comment]
ok, let me enquire again about the logistics on the W3C side...

**Comment by rayankans** [comment]
Thanks @marcoscaceres ([issue](https://github.com/w3c/webappswg/issues/30) for reference).

In the meanwhile, I filed issues against the following specs that use the Manifest's `ImageResource`:
- [Manifest](https://github.com/w3c/manifest/issues/854)
- [Background Fetch](https://github.com/WICG/background-fetch/issues/142)
- [Content Indexing](https://github.com/rayankans/content-index/issues/24)

**Comment by marcoscaceres** [comment]
Ok, we are live 🎉 

We can start looking at integrating with this spec. I’ll get it added to Shepherd so we can cross-reference it properly etc.

**Comment by aarongustafson** [comment]
Awesome! I'll also get to work on the follow up PR for adding an accessible description.

**Comment by marcoscaceres** [comment]
We are up! 
https://respec.org/xref/?term=ImageResource&specs=image-resource

**Comment by aarongustafson** [comment]
I believe we can close this as we are published and the references are in.
