### ISSUE TITLE
CFC for to publish FPWD

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/image-resource#17]
This is a Call for Consensus to publish a First Public Working Draft of the ImageResource specification:

https://w3c.github.io/image-resource/
 
The specification was spun out of the Web Manifest specification. 

The abstract reads:

> This document defines the concept of an "image resource" and a corresponding WebIDL ImageResource dictionary. Web APIs can use the ImageResource dictionary to represent an image resource in contexts where an HTMLImageElement is not suitable or available (e.g., in a Worker). 

The CFC ends on 3rd of April, 2019.

**Comment by travisleithead** [comment]
This is great, happy to see this abstraction moved out for improved sharing. Positive support from me!

**Comment by marcoscaceres** [comment]
CFC completed successfully. Publication was approved by W3C... should be on TR by the end of the week, if not sooner.
