### ISSUE TITLE
Merge with WICG/imageresource?

### ISSUE THREAD

**Issue by aarongustafson** [w3c/image-resource#2]
Totally missed that this stub exists: https://github.com/WICG/imageresource. We should talk to @marcoscaceres about merging this into that (or alternately deleting that when this moves over).

**Comment by marcoscaceres** [comment]
We should delete the WICG one, as we are spinning off the existing work into a new document... however, I need to check with the W3C about adding this new deliverable and what it means for our working group charter.

**Comment by marcoscaceres** [comment]
Deleted the other one :)
