### ISSUE TITLE
Which CSP policy should apply to ImageResource

### ISSUE THREAD

**Issue by danyao** [w3c/image-resource#25]
Migrating the conversation from https://github.com/w3c/manifest/issues/851

> The PaymentInstruments [1] concept was originally designed to support multiple credit cards. It adds confusion to payment handlers that are not fundamentally about credit cards. Since Payment Request API is moving towards payment apps being the atomic building blocks instead of instruments, I think it will be more clear to change payment handler registration interface to something like this:
> 
> registration.paymentManager.setPaymentMethods([
>     'https://bobpay.xyz/pay',
>     'https://alicepay.com'
> ]);
> Today many parts of PaymentInstruments are not used:
> 
> Web-based payment handlers usually sets a single instrument with their supported payment methods
> Chrome always fetches the icon from the payment handler's web app manifest instead of using the ones provided in PaymentInstruments.set()
> capabilities only has well-defined meaning for basic-card payment method
> With the proposed change to remove the PaymentInstrument concept, the web app manifest can become the authoritative source of information about the payment handler, such as name, icons, capabilities. This will also better unify just-in-time installation and explicit installation of payment handlers.
> 
> [1] https://w3c.github.io/payment-handler/#paymentinstruments-interface

The [Image resource](https://www.w3.org/TR/image-resource/#introduction) spec doesn't currently discuss CSP. Which CSP policy will govern the fetching of an image resource?

**Comment by rayankans** [comment]
The image resource [fetch algorithm](https://w3c.github.io/image-resource/#fetching-an-image-resource) requires a client to be provided.

The CSP of the client will be applied.

**Comment by danyao** [comment]
This is a great solution. Thank you!
