### ISSUE TITLE
Representing Spatial Icons for WebApps

### ISSUE THREAD

**Issue by aarongustafson** [w3c/image-resource#27]
Migrating https://github.com/w3c/manifest/issues/763

> As a part of immersive-web group, there is a proposal to use spatial / 3D favicons for immersive-web pages/apps. See explainer here: https://github.com/immersive-web/spatial-favicons/blob/master/explainer.md
> 
> WebApps manifest today has "icons" member in the manifest, but is restricted to "Image Resources" as per spec. Our initial idea was to "re-use" this member to spatial icons as well, except that the mime type will be a non-image mime type and the sizes will have additional dimension. But the WebApp manifest explicitly says: "Image Resources" and there is an associated algorithm to handle intelligent fetching on need basis.
> 
> There are couple of approaches:
> 
> 1. Extend the "icons" member to include Non Image Resources.
> 2. Introduce a new "spatial-icon" member to avoid any confusion and let the "platform"/ User Agent make an appropriate decision on which resource to use.
> 
> We are open to other ideas and hoping to get some feedback from WebApp manifest spec authors.

Agreed to option 1 with a dependency on the HTML spec being updates to allow for 3D values in `sizes` (as this spec references that one):

```json
{
    "src": "asset/high-lod.glb",
    "type": "model/gltf-binary",
    "sizes": "60x60x60"
}
```

**Comment by AdaRoseCannon** [comment]
It would be really great to have some follow up on this as Immersive Web browsers are produced with support for PWAs this will be a great thing to have clarity for.

**Comment by aarongustafson** [comment]
Tracking https://github.com/whatwg/html/issues/4922

**Comment by aarongustafson** [comment]
As [`ImageResource` parses the `sizes` attribute based on acceptable values for `sizes` in HTML](https://w3c.github.io/image-resource/#sizes-member), I am going to close this. Once HTML supports a 3rd dimension, we will as well.
