### ISSUE TITLE
Add image-resource to MDN data

### ISSUE THREAD

**Issue by aarongustafson** [w3c/image-resource#29]
https://github.com/mdn/browser-compat-data

Not sure where we should file it, though. Thoughts?

**Comment by marcoscaceres** [comment]
I'd file this over on MDN... they are probably best placed to help us figure out how this should be documented and the data captured.

**Comment by aarongustafson** [comment]
Added to MDN: https://github.com/mdn/browser-compat-data/issues/8938

Closing on our end.
