### ISSUE TITLE
Should this include "purpose" and "platform" from Manifest (and also Bikeshed vs Respec)

### ISSUE THREAD

**Issue by mgiuca** [w3c/image-resource#4]
The current ImageResource spec is missing the "purpose" and "platform" members from the Manifest spec. I'm not sure about "platform" (TBH I'd like to deprecate that), but "purpose" is quite important, especially for defining [maskable icons](https://www.w3.org/TR/appmanifest/#icon-masks).

Is the intention that the definitions of individual purposes (currently "badge" and "maskable") will continue to live inside the Manifest spec? Or will those also be migrated to the ImageResource spec (which was my original understanding).

A few follow-ups on this:

- It seems that ImageResource spec will largely be sliced out of the Manifest spec, and there are a lot more things, such as the entire "Icon masks and safe zone" section of that spec, that should be migrated into this one. That means a fair amount of work translating from Respec to Bikeshed. Could we not simply have this spec in Respec since it's forked off from Manifest?
- If the purpose: maskable stuff is going to be in this spec, I would like either @kenchris or myself or both to be editors of ImageResource (since we are the authors of that feature and want to continue maintaining it).

**Comment by NotWoods** [comment]
Since `purpose` is planned to be used in multiple locations in the manifest (launcher icons, shortcut icons) I think it makes sense to migrate here. I'd expect future uses of ImageResource will also benefit from purpose.

**Comment by mgiuca** [comment]
There's still a question of whether ImageResource spec should simply say "purpose" as a generic field, telling each spec to define what purposes are allowed in that context, or whether we should migrate all the purposes over from Manifest into the ImageResource spec.

**Comment by kenchris** [comment]
Well we want to keep them aligned as much as possible. Why not migrate over what is considered generic, like maskable.

**Comment by rayankans** [comment]
We talked about this briefly in TPAC, and we decided that `purpose` was too closely related to Manifest to include in this generic dictionary. Future fields that might be added (which would be beneficial to any spec using it) are things like alt-text or color-scheme. 

The current plan is to keep `purpose` in the Manifest spec with the maskable stuff. I don't imagine a generic user of `ImageResource` will need all of those. Manifest, and other specs, can add extra fields they need by extending the `ImageResource` dictionary, like so
```webidl
dictionary ManifestImageResource : ImageResource {
  USVString purpose;
};
```

@kenchris @mgiuca, since you both worked on the maskable stuff, how generic do you think those concepts are? I'm not sure Background Fetch or Content Indexing (current users of `ImageResource`) would need or use a purpose member as defined in the Manifest spec.

**Comment by mgiuca** [comment]
We could do that. But @marcoscaceres should have a say in this because he's trying to migrate Manifest spec away from WebIDL towards a more JSON-schema-like concept. I'd be interested to see how you'd do a "subclass" type of thing in that world.

> @kenchris @mgiuca, since you both worked on the maskable stuff, how generic do you think those concepts are? I'm not sure Background Fetch or Content Indexing (current users of `ImageResource`) would need or use a purpose member as defined in the Manifest spec.

I'm not too familiar with these; I had a brief look at Background Fetch and it looks like they're using it for a UI icon. In that case, it's entirely possible that they'll want some "purpose" in the future for customizing how the icon is displayed in some OS contexts. Perhaps even Maskable would be useful, because some OS may wish to display the Background Fetch UI in a context where the OS wants to control the shape of the icon, just like we have with Manifest app icons.

We have three choices;

1. Make "purpose" entirely specific to Manifest.
2. Make the "purpose" field, as a string, part of Image Resource but have each spec define what purposes it supports.
3. Define all the purposes (currently, "any", "badge" and "maskable") in the Image Resource spec which makes them available everywhere.

I think we should at least do 2. 3 I'm not sure about (particularly from an editorial perspective, as I've been saying it's hard to convert from Respec to Bikeshed all of the material relating to maskable icons, and I would also want to retain editorship over that part of the spec if it were moved into Image Resource). So perhaps for now we would go with 2 until some other spec indicates a need for a maskable purpose, then we could move that into Image Resource.

**Comment by rayankans** [comment]
I still disagree we should have a field _that_ general in the spec.

Having an ambiguous `purpose` field which specs have to define & constrain adds unnecessary overhead, which can be easily mitigated by having specs which need it (or something similar) extending `ImageResource`.

So that being said, I'd prefer going for option 1 or 3. I'm leaning towards 1, since again, I'm still not convinced `purpose` as defined in the Manifest will be used in other specs. 3 should also not be an issue @mgiuca since I'll be porting the spec over to ReSpec.

@jakearchibald Do you have any thoughts on how `purpose` ties in with Background Fetch?

**Comment by NotWoods** [comment]
`icons` in Background Fetch currently display as a "large icon" in Android notifications (red box). It might be worthwhile to let the "small icon" (green box) be controlled as well via `purpose`.

<img width="269" alt="Screen Shot 2019-10-07 at 6 12 49 PM" src="https://user-images.githubusercontent.com/1782266/66360051-73ad1080-e92e-11e9-8df1-3e84e9314d42.png">

Android also lets images be expanded to a "big picture" which is another field that could be targeted.

<img alt="" src="https://developer.android.com/images/ui/notifications/template-image_2x.png" width="269">

**Comment by mgiuca** [comment]
@marcoscaceres :
> It's just a flat object structure, so there would be no subclassing... just properties on an object.

If we did Option 1, then "subclassing" (of some sort) would be needed, so the Image Resource spec provides an `ImageResource` class, then Manifest spec provides a `ManifestImageResource` subclass which extends `ImageResource` but adds `purpose` and `platform` members.

I think Option 1 is probably the best for now, as it's the conservative option (we can move to 3 later). If we did 3 right away, it would immediately make `purpose: maskable` and friends available to all specs that use `ImageResource`. Technically that wouldn't mean any user agent needs to implement that (for example, if a Background Fetch image specifies a `purpose: maskable`, all user agents could ignore it), but it would mean that a user agent _could_ unilaterally decide to honour a purpose: maskable in a Background Fetch image without needing any spec changes. We probably don't want to allow that, unless the Background Fetch spec folks decide that it's wanted.

Option 1 also allows us to keep the big section on purpose: maskable in the Manifest spec, which is nice because that's where it will mostly be used. There's just the question of whether we can do that "subclass" thing, from a technical standpoint. In WebIDL, it's easy:

```idl
dictionary ManifestImageResource : ImageResource {
  USVString platform;
  USVString purpose;
}
```

I'm just wondering if @marcoscaceres you can engineer an equivalent thing in whatever scheme you are planning to migrate the dictionaries to.

**Comment by aarongustafson** [comment]
> I think Option 1 is probably the best for now, as it's the conservative option (we can move to 3 later).

100% agree on this.

**Comment by aarongustafson** [comment]
::bump:: to @marcoscaceres for feedback on this.

**Comment by marcoscaceres** [comment]
Sorry for the delay... option 1 seems good, with @mgiuca suggestion that we can always migrate to option 3 later.

**Comment by aarongustafson** [comment]
Ok, so the plan of record is to subclass `ImageResource` within the manifest as @mgiuca proposed [here](https://github.com/w3c/image-resource/issues/4#issuecomment-540271196).
