### ISSUE TITLE
Should this include the Fetching algorithm?

### ISSUE THREAD

**Issue by rayankans** [w3c/image-resource#5]
The Fetching algorithm is simple enough:
1. Create custom Request
2. Fetch request

Different users of `ImageResource` would create `Request` objects with different properties (for example `service-worker mode`).

Would it make sense to try and consolidate the common properties as much as possible and pass the others as parameters to a generic Fetching algorithm?

**Comment by aarongustafson** [comment]
I think it makes sense to include bare bones instructions. If nothing else it gives future specs that might like to use this feature a starting point.

**Comment by rayankans** [comment]
Makes sense. I'll wait for PR #6 to go through, and I'll build on top of that

**Comment by aarongustafson** [comment]
I just merged the processing stuff if you’d like to add this bit now @rayankans.
