### ISSUE TITLE
Add alternative text member

### ISSUE THREAD

**Issue by aarongustafson** [w3c/image-resource#7]
I am leaning toward calling it `description` (leaning on Manifest a bit) as opposed to the more HTML-centric `alt`. I will make it optional but also declare it to be highly recommended unless the same information can be provided in some other way (using the manifest `name` & `icons` as an example).

**Comment by NotWoods** [comment]
Is this property necessary? As far as I'm aware, the only uses of ImageResource right now are decorative. (app icons, notification images) 

^ In these two scenarios I don't think Android lets you set description text for the images.

**Comment by aarongustafson** [comment]
@NotWoods `ImageResource` elements supplied as part of the `screenshots` member need descriptions. In future, `ImageResource` may be used to supply images for in rich notifications and they would also need alternative text. The Web Payments API may also make use of `ImageResource` and could use this property.

**Comment by aarongustafson** [comment]
@marcoscaceres Could I get your eyes on [the changes I’m suggesting to address this](https://github.com/w3c/image-resource/commit/02ea80852239720cd4dd9e1db5ce35b1eb1a5a36)? In particular, I’m not sure how to go about referencing the possible external value (as in the case of `{{WebAppManifest/name}`} being used to provide the `description` for members of the `{{WebAppManifest/icons}}` array). What I was trying to do was define an external description that could be subbed in if no explicit `description` is provided for a given resource.

**Comment by johnfoliot** [comment]
I will caution this group on the choice of "description", which is already something of [a reserved term in ARIA](https://www.w3.org/TR/wai-aria-1.1/#namecalculation) (Accessible Description, aka aria-describedby), a spec that also has the concept of an Accessible Name (aka `aria-label`, `aria-labeledby`, `alt`)

Generally speaking, [all non-textual elements will require an accessible name](https://www.w3.org/TR/WCAG21/#non-text-content), however **only complex graphics** require an accessible description. If the desire is to avoid using the more HTML-centric term of `alt`, then I would suggest instead you contemplate using `label` .

Additionally, the code example at https://www.w3.org/TR/image-resource/#imageresource-dictionary suggests the following
     
```
     const image = {
     src: "path/to/image.ico",
     sizes: "16x16 32x32 64x64",
     type: "image/vnd.microsoft.icon",
     };

```
There is a real possibility that authors may provide alternative images at different sizes, which would potentially require different text alternatives depending on the image rendered. As such, a mechanism that binds different text alternatives to different sizes is highly desirable. (For example in the code snippet above, there may be potential 3 different '_accessible names_'  depending on the image shown based on size).

Proposal (suggestion?):
```
     const image = {
     src: "path/to/image.ico",
     sizes: "16x16 32x32 64x64",
     label "small name, medium name, large name",
     type: "image/vnd.microsoft.icon",
     };

```

**Comment by aarongustafson** [comment]
Great suggestions @johnfoliot! I was not wedded to the name of the key and I like the suggestion of allowing for multiple label values. 

On that note, I wonder if comma separation would be flexible enough. Yes, ideally they should be short labels, but I'm trying to think of scenarios where there may be a necessary comma in the label. Perhaps something like a web app shortcut for a person, where the avatar label would be their family name followed by their given name? There may be other, more compelling scenarios, but that was the first to pop into my head.

**Comment by johnfoliot** [comment]
Hmmm, good point. 

Normally attributes take either space-separated or comma-separated values IF they take multiple values, but I suppose any character would suffice, as long as all the 'players' (user-agents, AT, etc.) agree. What about the pipe character? (label="small name | gustafson,a | large name")

Thoughts?

**Comment by aarongustafson** [comment]
@johnfoliot In discussing this a bit more, we’re going to forgo the added complexity of supporting multiple `label` values. Instead, `label` will be specced as a string supporting a single value. Here’s our logic:

1. Not many authors presently use .ico where `ImageResource` is in play (especially when compared to favicon).
2. .ico packages requiring unique Accessible Names for each size are an edge case.
3. If the desired result is for different icon sizes to have different Accessible Names, this can be achieved by providing multiple `ImageResource` objects (as the Manifest already recommends), which can each be given the appropriate Accessible Name (or none, if the Accessible Name can be inferred from the context).

As an aside, we suspect that the future will see more developers opting for SVG over .ico in order to produce better icon representations overall. SVG will also enable the different icon sizes to be given Accessible Names as needed. To that end, I’ll be sure to add a note about extracting the Accessible Name from image formats that support that feature.

Does that resolve the issue for you?

**Comment by johnfoliot** [comment]
WFM.

I am presuming from this response then that you are accepting the proposal of using `label` to furnish the Accessible Name (an enthusiastic +1), but foregoing multiple values (I can live with this).

**Comment by aarongustafson** [comment]
You got it. Thanks @johnfoliot!

**Comment by johnfoliot** [comment]
Note: advising ARIA WG at W3C about this, to ensure that the accessible name mechanism ( `label` ) proposed is [mapped to the Core AAM](https://www.w3.org/TR/core-aam-1.2/) @joanmarie 
(Not sure if that is required, but better a simple head's up than silence, ya?)

**Comment by joanmarie** [comment]
@johnfoliot Thanks! I wonder where the right place for this would be. The name calculation belongs in https://w3c.github.io/accname/, but specific specs can override them, e.g.:

* https://w3c.github.io/html-aam/#accessible-name-and-description-computation
* https://w3c.github.io/svg-aam/#mapping_additional_nd

If there's not going to be an accessible object for the label itself, I don't *believe* that this belongs in Core-AAM.

**Comment by johnfoliot** [comment]
Hi @joanmarie - I now acknowledge being in a space I don't know enough about. 

Wondering aloud if @aarongustafson can run this ball himself, or perhaps you can help him if required. At the end of the day, I grok that screen readers will need to know that `image-resource` will have an accessible name furnished via `label` - how you extract that to the end user is beyond my skill set.

(That, and if you want something done, give it to a busy person ;-) )

**Comment by joanmarie** [comment]
Once there's a real-world test case with a browser implementation I can try, I should have a better idea of what spec might need to be changed and what language might need to be used.
