### ISSUE TITLE
Processing an array of image resources does not return an Array of ImageResources

### ISSUE THREAD

**Issue by rayankans** [w3c/image-resource#8]
In [processing an array of image resources](https://w3c.github.io/image-resource/#processing-an-array-of-image-resources), processing the `src` and the `sizes` fields return a URL and Set respectively. This means the returned objects are not valid `ImageResource`s.

@aarongustafson, do you think it makes sense to define a processed image resource struct, or just return a generic Object? I'm leaning towards a processed image resource ATM.

**Comment by aarongustafson** [comment]
Good catch. I don’t have a preference.
